# LOCAL DATABASE CONFIGURATION (H2 IN-MEMORY)
# ===============================
spring.datasource.url=jdbc:h2:mem:beemagicdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# RAZORPAY LOCAL CONFIGURATION
# ===============================
razorpay.key.id=rzp_test_TI1JLmHT3Qicq1
razorpay.key.secret=cYglPECObSZU0Kbf6azZDF3Y

# MAIL CONFIGURATION (SMTP)
# ===============================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:beemagic777@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:okxcoysbgxhqtkmm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
